### ISSUE TITLE
Is `relationMappings` required on all models involved in relation-based queries?

### ISSUE THREAD

**Issue by arist0tl3** [IlyaSemenov/objection-graphql-resolver#1]
First off -- awesome project! I literally started walking down the steps of building this myself as I wanted to support naive resolution without needing to reference the entire tree at each top level query. And then a bit of googling later, found myself testing this out =)

Anyway, more of a question than anything. I'm curious if the `relationMappings` getter is required on all models? I was really struggling to get this package working until I dove in and looked around `get_field_resolver` and saw that my models weren't looking the same and lookups were failing.

It could be cool to expand the readme with some examples that include the objection models. I'm working on a scaffold right now that could be a source of content for something like that if you're interested.

Cheers!

**Comment by IlyaSemenov** [comment]
Sorry - I missed your question. Since I believed no one was using the library besides me and my team, I never looked here. :)

Yes, `relationMappings` is required for the models where you want to traverse relations... This is how objection.js works, after all. If I'm missing a use case where you don't actually need `relationMappings` for objection.js but it's somehow needed for graphql resolver, please elaborate with an example.

**Comment by arist0tl3** [comment]
No worries! Its definitely a cool library, I wouldn't be surprised for others to find it helpful.

My use case is basically:

I have three tables, A, B, and C. A and B are related but C is just a standalone table with no relations. I want to keep consistent patterns and always use `resolveGraph` in my resolvers. That requires me to define an empty `relationMappings` to keep this package happy:

```
export default class CModel extends Model {
  static tableName = 'c';

  static get modelPaths() {
    return [__dirname];
  }

  id!: string

  // This needs to be defined even if there are no relations
  static get relationMappings() {
    return {};
  }
}
```

Maybe this is a weird use case and you're only resolving with `resolveGraph` when you know there are nested queries/relationships on the model in question?

**Comment by IlyaSemenov** [comment]
This is definitely not a weird case, let me come up with a regression test and see why it's not happy.

**Comment by arist0tl3** [comment]
Thanks for taking a look at this! Will give it a test myself later today =)
