### ISSUE TITLE
filtering with >, <, >=, <=, etc.

### ISSUE THREAD

**Issue by randomiser** [IlyaSemenov/objection-graphql-resolver#15]
Hi there,

Still loving this library. Super useful and working well.

In the filters area you have this comment:

"TODO: lt, gt, lte, gte, like, ilike, contains, icontains"

Is that something you're likely to consider adding? Those would be useful to have available.

Thanks in advance,
Matt

**Comment by IlyaSemenov** [comment]
Yes, this is easily extensible at https://github.com/IlyaSemenov/objection-graphql-resolver/blob/fea85fbb580ce4113fdd0626820ecb6956ddd11f/src/filter.ts#L60 by analogy. If you have some spare time for the PR I'd gladly merge it.
