### ISSUE TITLE
Mutations

### ISSUE THREAD

**Issue by randomiser** [IlyaSemenov/objection-graphql-resolver#6]
Hi Ilya,

Thanks for building this great looking library. Looking forward to using it with my project. 

I noticed your documentation, examples and tests make no mention of mutations. 

Is that because it’s not currently supported? Or if it is could you add an example scenario to the documentation?

Thanks in advance,
Matt

**Comment by IlyaSemenov** [comment]
@randomiser Thank you for the feedback!

Mutations are fully supported. The library operates on a different level: it provides a helper to be used in a _resolver_. From the server's point of view, there's no difference between queries and mutations, they are both resolvers and operate identically.

That said, I agree that the examples may be confusing as they never mention any mutation. I will amend the documentation.

To give you the generic idea, the code will look something like:

```ts
const typeDefs = gql`
  ...
  type Mutation {
    add_post(text: String!): Post!
  }
`

const resolvers = {
  Query: {
    ...
  },
  Mutation: {
    add_post(parent, args, ctx, info) {
      const { text } = args
      const post = await Post.query().insert({ text })
      return resolveGraph(ctx, info, post.$query())
    },
  },
}
```

**Comment by IlyaSemenov** [comment]
6a80630a24a5c9379cd910d1bbd73af5d89f3847: I updated the minimal all-in-one example to include an example of a mutation resolver. (I also updated it to actually fully function.)
