### ISSUE TITLE
ModelResolver modifier issue

### ISSUE THREAD

**Issue by randomiser** [IlyaSemenov/objection-graphql-resolver#8]
Hi again IIya,

I'm totally loving this library. Making my GraphQL project super productive. Have found another issue however.

All of my model resolvers have this modification added to exclude any virtually deleted records

const defaultOptions = {
  modifier: (query, args) => query.whereNull('deletedAt')
}

I.e.

export const Person = ModelResolver(PersonModel, defaultOptions)
export const Company = ModelResolver(CompanyModel, defaultOptions)
export const Office = ModelResolver(OfficeModel, defaultOptions)

Assuming a person works at a company and a company has multiple offices.

When I query the above I get a SQL error saying:

and `deletedAt` is null - Column 'deletedAt' in where clause is ambiguous",

Hope that's something you could take a look at.

Cheers,
Matt

**Comment by randomiser** [comment]
Hi sorry I closed this by mistake.

**Comment by IlyaSemenov** [comment]
Since you're building your own query filter here I don't see how the library may possibly help. The resulting SQL query that _you_ have extended is ambiguous... so you need to take care of this.

I'd suggest to use per-model options:

```ts
export const Person = ModelResolver(PersonModel, {
  modifier: (query) => query.whereNull(ref('person.deletedAt'))
})

export const Company = ModelResolver(CompanyModel, {
  modifier: (query) => query.whereNull(ref('company.deletedAt'))
})
```

**Comment by randomiser** [comment]
I realised today (after I was away from my computer) I could do what you've suggested and was just testing it this very moment.

Was about to close this and saw your comment. Thanks for that and apologies for wasting your time.
