### ISSUE TITLE
Enable filters in model resolver

### ISSUE THREAD

**Issue by randomiser** [IlyaSemenov/objection-graphql-resolver#9]
Howdy again,

Following the docs for filtering I'm attempting to filter at a deep level only.

When I attempt to call queries that involve several levels of joins such as the following the query isn't amended to include the filter I've included and returns all of the records.

I've switched on filter: true for all models and set it at the resolver level, and updated the GQL to include the filter options.

I notice your docs state "TODO" against some of the extra filtering options. Should this case work currently? I've tried other variants like status__in: [pending] and adding a modifier to the model directly and calling that.

```
{
	"query": "query NotWorkingExample { 
			companies { 
				offices { 
					staffMembers { 
						firstName 
						lastName
						expenses(filter: {status: pending}) { 
							id 
							status 
						} 
				}
			} 
		} 
	}"
}
```

_EDIT: added code formatting - Ilya_

**Comment by IlyaSemenov** [comment]
@randomiser I added demo test for the case (see the link to commit above) - nested filter works for me. Please check what's different with your case.

> I notice your docs state "TODO" against some of the extra filtering options. Should this case work currently?

It should, but it's currently either "all in" or fully disabled (which is the default). Ideally it should allow fine-grained setup so that filtering only on certain fields could be enabled. Otherwise, it might introduce a security risk in certain cases.

**Comment by randomiser** [comment]
Hi Ilya,

I was basing my assumptions on how this worked on this document:

https://github.com/IlyaSemenov/objection-graphql-resolver/blob/master/docs/filters.md

I hadn't realised I would need to explicitly add a RelationResolver into the ModelResolver to get this working. Now I've made the change as per your test it's working fine. Thank you!

Suggest you could add this RelationResolver information into the filters.md documentation. Would stop questions like this happening again.

Thanks again, great library!
Matt

**Comment by IlyaSemenov** [comment]
I see. So two problems here:
1) The documentation is plain wrong.
2) Enabling filters on model resolver level (or even on graph resolver level) actually makes sense.

I'll take care of this.

**Comment by IlyaSemenov** [comment]
It's now possible to set `allowAllFilters: true` on model and graph level (see examples).

Unfortunately, that means migrating to the new API. (In fact, it's possible to back-port that to the old API which is still supported.)
